### PR TITLE
Fix transmission interface tinyxml build error

### PR DESCRIPTION
**Pull request by davetcoleman**
Second try, based on https://github.com/ros-controls/ros_control/pull/92

Fix for:

```
/tmp/buildd/ros-hydro-transmission-interface-0.5.0-0precise-20130719-0615/include/transmission_interface/transmission_info.h:48:21: fatal error: tinyxml.h: No such file or directory
```

### CODE REVIEW

**Comment by davetcoleman** [comment]
@wjwwood do you think this will fix our linking error in bloom? i don't understand why it works fine on our local computers but not in the build farm

**Comment by wjwwood** [comment]
It might, the reason is that on the farm things are built in isolation, meaning you build each package, install it, and then build the next. On your local machine you are likely building them together in a workspace. This can hide problems with missing includes on headers and linking on libraries.

**Comment by davetcoleman** [comment]
How can i best replicate the build farm environment for fixing these build errors? Just now I tried these steps:
1. Only sourced my hydro/setup.bash
2. Created a new empty workspace
3. Added the ros_control repo (includes several packages)
4. catkin_make_isolated

Everything built fine, so I can assume my CMakeList.txt changes have fixed the transmission problem we had earlier?

**Comment by wjwwood** [comment]
That is likely the case.

We have plans to make it easier to replicate the build farm's environment, but it's pretty low on the priority list at the moment.

**Comment by wjwwood** [comment]
So I just reread the thread, The problem with your above test (how it differs from the farm), is that you might have headers of dependencies installed into `/opt/ros/hydro/include` which you package does not directly declare.

The farm starts with nothing installed, then it installs the the dependencies of the package it's building from apt-get, and then sources the setup.bash file and builds.

For example, consider you had a package `foo` which used a header from package `bar`, but `bar` was not listed as a dependency in the package.xml of `foo`. On the farm this will fail, because it will not install `bar` and `foo` will not find the header from `bar`. However, if you have `bar` installed on your local machine (you installed it manually, or some other package installed it), `foo` might find the header it needs in `/opt/ros/hydro/include` even though it doesn't depend on `bar`.

To really test this locally you can do a pbuilder environment (like the farm) or build everything from source. For the latter you need all of the packages from source in one workspace, do not source /opt/ros/hydro/setup.bash, and then call `catkin_make_isolated` (explicitly without the `--install` option).

Setting up a pbuilder environment locally isn't trivial, so I wouldn't recommend that. @tfoote might know how to set that up, but I really don't have a good idea of how to do that.

**Comment by davetcoleman** [comment]
Thanks for the explanation! I think pbuilder is def. out of range of the time I want to put into this. For now I'll just merge this and see if the latest fixes build, otherwise I'll install all of the packages from source in one work space.
